import { Exercise } from './types';

export const EXERCISE_DATABASE: Exercise[] = [
  {
    id: 'copenhagen_plank',
    name: 'Copenhagen plank',
    target: 'Adducteurs',
    description: 'Allongé sur le côté, pose le pied du dessus sur l\'assise d\'une chaise. Soulève le bassin pour aligner tête, bassin et pieds. La jambe du dessous reste dans le vide. Change de côté à mi-temps.',
    equipmentRequired: ['chaise'],
    category: 'specific_adductor',
    group: 'adducteurs',
    tips: 'L\'effort se sent à l\'intérieur de la cuisse posée sur la chaise.',
    instructionHighlight: 'Corps aligné, bassin haut.',
    easier: 'Pose le genou sur la chaise au lieu du pied.',
    harder: 'Monte et descends la jambe du dessous pendant le gainage.',
  },
  {
    id: 'calves_standing_slow',
    name: 'Mollets debout, descente lente',
    target: 'Mollets (gastrocnémiens)',
    description: 'Sur une marche, talons dans le vide. Monte sur la pointe des pieds en 1 seconde, redescends en 3 à 4 secondes.',
    equipmentRequired: [],
    category: 'specific_calf',
    group: 'mollets',
    tips: 'C\'est la descente qui compte : ce travail excentrique renforce le mollet et le tendon d\'Achille.',
    instructionHighlight: '1 s pour monter, 4 s pour descendre.',
    easier: 'Sur le sol plat, une main contre le mur.',
    harder: 'Sur une jambe, l\'autre pied replié derrière. Change de jambe à chaque tour.',
  },
  {
    id: 'calves_seated',
    name: 'Mollets assis',
    target: 'Mollets (soléaire)',
    description: 'Assis sur une chaise, ton poids posé sur les cuisses près des genoux. Monte sur la pointe des pieds le plus haut possible, puis redescends. Enchaîne.',
    equipmentRequired: ['chaise', 'poids_8kg'],
    category: 'specific_calf',
    group: 'mollets',
    tips: 'Genoux pliés, c\'est surtout le soléaire qui travaille. C\'est lui qui tient la cheville à chaque foulée.',
    instructionHighlight: 'Amplitude complète, descente contrôlée.',
    easier: 'Sans poids, en appuyant les mains sur les cuisses.',
    harder: 'Une jambe à la fois, le poids sur le genou qui travaille.',
  },
  {
    id: 'squat_sumo',
    name: 'Squat sumo',
    target: 'Adducteurs et quadriceps',
    description: 'Pieds plus écartés que les épaules, pointes tournées vers l\'extérieur. Descends en gardant le buste droit, puis remonte.',
    equipmentRequired: [],
    category: 'specific_adductor',
    group: 'adducteurs',
    tips: 'Pousse les genoux vers l\'extérieur pour qu\'ils restent dans l\'axe des pieds.',
    instructionHighlight: 'Genoux dans l\'axe des pieds, buste droit.',
    easier: 'Descends moins bas, mains sur les hanches.',
    harder: 'Tiens ton poids contre la poitrine et marque 2 s en bas.',
  },
  {
    id: 'lateral_lunges',
    name: 'Fentes latérales',
    target: 'Adducteurs et stabilité du genou',
    description: 'Fais un grand pas sur le côté. Plie la jambe qui avance, garde l\'autre tendue, puis pousse pour revenir au centre. Alterne les côtés.',
    equipmentRequired: [],
    category: 'specific_adductor',
    group: 'adducteurs',
    tips: 'Envoie les fesses en arrière sur la jambe pliée, comme pour t\'asseoir.',
    instructionHighlight: 'Jambe opposée tendue.',
    easier: 'Fais un pas plus petit et descends moins bas.',
    harder: 'Tiens ton poids contre la poitrine.',
  },
  {
    id: 'plank_commando',
    name: 'Planche commando',
    target: 'Gainage profond (transverse)',
    description: 'En planche sur les avant-bras. Monte sur une main puis sur l\'autre pour passer bras tendus, puis redescends sur les avant-bras. Alterne le bras qui commence.',
    equipmentRequired: [],
    category: 'abdos',
    group: 'gainage',
    tips: 'Le bassin ne doit pas se balancer d\'un côté à l\'autre.',
    instructionHighlight: 'Bassin immobile.',
    easier: 'Sur les genoux, ou pieds plus écartés.',
    harder: 'Pieds joints, et plus lentement.',
  },
  {
    id: 'woodchop',
    name: 'Bûcheron avec poids',
    target: 'Obliques et gainage debout',
    description: 'Debout, pieds largeur d\'épaules, ton poids à deux mains près de la hanche gauche. Monte-le en diagonale au-dessus de l\'épaule droite en pivotant sur le pied arrière, puis redescends en contrôlant. Change de côté à mi-temps.',
    equipmentRequired: ['poids_8kg'],
    category: 'abdos',
    group: 'gainage',
    tips: 'Le mouvement vient du buste et des hanches. Les bras restent presque tendus, le dos reste droit.',
    instructionHighlight: 'Buste gainé, descente contrôlée.',
    easier: 'Sans poids, mains jointes.',
    harder: 'Redescends en 3 secondes.',
  },
  {
    id: 'squat_classic',
    name: 'Squat',
    target: 'Quadriceps et fessiers',
    description: 'Pieds largeur d\'épaules. Descends en envoyant les fesses en arrière, comme pour t\'asseoir, puis remonte.',
    equipmentRequired: [],
    category: 'general',
    group: 'cuisses',
    tips: 'Garde le poids du corps sur les talons et le regard devant toi.',
    instructionHighlight: 'Dos droit, talons au sol.',
    easier: 'Descends jusqu\'à toucher une chaise, puis remonte.',
    harder: 'Ton poids contre la poitrine, 3 secondes pour descendre.',
  },
  {
    id: 'alternating_lunges',
    name: 'Fentes alternées',
    target: 'Quadriceps, fessiers et équilibre',
    description: 'Fais un grand pas en avant et descends jusqu\'à ce que le genou arrière frôle le sol, puis reviens. Alterne les jambes.',
    equipmentRequired: [],
    category: 'general',
    group: 'cuisses',
    tips: 'Garde le buste vertical et le genou avant dans l\'axe du pied.',
    instructionHighlight: 'Les deux genoux à 90°.',
    easier: 'Descends moins bas, une main contre un mur.',
    harder: 'Tiens ton poids à deux mains contre la poitrine.',
  },
  {
    id: 'wall_sit',
    name: 'Chaise contre un mur',
    target: 'Quadriceps et mollets',
    description: 'Dos contre le mur, cuisses parallèles au sol. Tiens la position.',
    equipmentRequired: [],
    category: 'general',
    group: 'cuisses',
    tips: 'Tout le dos reste en contact avec le mur.',
    instructionHighlight: 'Cuisses parallèles au sol.',
    easier: 'Remonte un peu : cuisses moins basses.',
    harder: 'Décolle un talon puis l\'autre, ou pose ton poids sur les cuisses.',
  },
  {
    id: 'step_up',
    name: 'Montée sur chaise',
    target: 'Quadriceps, fessiers et poussée',
    description: 'Pose un pied sur une chaise stable, calée contre un mur. Pousse sur ce pied pour monter, sans t\'aider de la jambe du bas, puis redescends lentement. Change de jambe à mi-temps.',
    equipmentRequired: ['chaise'],
    category: 'general',
    group: 'cuisses',
    tips: 'Toute la poussée vient de la jambe posée sur la chaise. En haut, monte le genou de l\'autre jambe comme dans la foulée.',
    instructionHighlight: 'Pousse dans le pied du haut.',
    easier: 'Sur une marche d\'escalier au lieu de la chaise.',
    harder: 'Ton poids contre la poitrine, 3 secondes pour redescendre.',
  },
  {
    id: 'pushups',
    name: 'Pompes',
    target: 'Haut du corps et gainage',
    description: 'Mains sous les épaules, corps gainé. Descends la poitrine près du sol, puis pousse.',
    equipmentRequired: [],
    category: 'general',
    group: 'haut_du_corps',
    tips: 'Coudes à environ 45° du corps, pas écartés à l\'horizontale : tes épaules te remercieront.',
    instructionHighlight: 'Corps droit du début à la fin.',
    easier: 'Sur les genoux, ou mains posées sur une chaise.',
    harder: 'Descends en 3 secondes, ou pose les pieds sur une chaise.',
  },
  {
    id: 'jumping_jacks',
    name: 'Jumping jacks',
    target: 'Cardio et mollets',
    description: 'Saute en écartant les pieds et en levant les bras au-dessus de la tête, puis reviens pieds joints, bras le long du corps.',
    equipmentRequired: [],
    category: 'general',
    group: 'cardio',
    tips: 'Atterris en souplesse sur l\'avant du pied.',
    instructionHighlight: 'Réceptions légères.',
    easier: 'Sans sauter : écarte un pied puis l\'autre.',
    harder: 'Plus vite, réceptions toujours légères.',
  },
  {
    id: 'high_knees',
    name: 'Montées de genoux',
    target: 'Cardio et posture de course',
    description: 'Cours sur place en montant les genoux à hauteur de hanches. Les bras accompagnent comme en course.',
    equipmentRequired: [],
    category: 'general',
    group: 'cardio',
    tips: 'Reste grand, appuis rapides sur l\'avant du pied.',
    instructionHighlight: 'Buste droit, appuis rapides.',
    easier: 'En marchant, genou haut à chaque pas.',
    harder: 'Plus vite, genoux plus hauts.',
  },
  {
    id: 'pogo_jumps',
    name: 'Sauts sur place pieds joints',
    target: 'Tendon d\'Achille et mollets',
    description: 'Pieds joints, saute sur place en rebondissant sur l\'avant du pied, jambes presque tendues. Les talons ne touchent pas le sol.',
    equipmentRequired: [],
    category: 'general',
    group: 'cardio',
    tips: 'Comme un ressort : le moins de temps possible au sol. Le même travail que la corde à sauter, sans corde.',
    instructionHighlight: 'Talons décollés, rebonds courts.',
    easier: 'Sauts plus bas, avec une petite pause entre chaque.',
    harder: 'Sur un pied, en changeant de pied à chaque tour.',
    caution: 'À éviter en cas de douleur au tendon d\'Achille ou au mollet. Commence par des séries courtes.',
  },
  {
    id: 'calf_raise_isometric_low',
    name: 'Mollets en squat profond',
    target: 'Mollets (soléaire)',
    description: 'Accroupis-toi au plus bas, fesses près des talons. Monte sur la pointe des pieds, tiens 2 secondes, repose les talons. Enchaîne.',
    equipmentRequired: [],
    category: 'specific_calf',
    group: 'mollets',
    tips: 'Genoux très pliés, c\'est le soléaire qui travaille.',
    instructionHighlight: 'Tiens 2 s en haut.',
    easier: 'Tiens-toi à un meuble pour l\'équilibre.',
    harder: 'Tiens 5 secondes en haut.',
  },
  {
    id: 'sauts_corde_bas',
    name: 'Corde à sauter, pieds joints',
    target: 'Tendon d\'Achille et mollets',
    description: 'Petits sauts rapides sur l\'avant du pied, jambes presque tendues. Les talons ne touchent pas le sol.',
    equipmentRequired: ['corde_a_sauter'],
    category: 'specific_calf',
    group: 'mollets',
    tips: 'Cherche des rebonds courts et réguliers : le tendon d\'Achille travaille comme un ressort.',
    instructionHighlight: 'Talons décollés, rebonds courts.',
    easier: 'Plus lentement, avec un petit rebond entre chaque tour de corde.',
    harder: 'Plus vite, ou passe à la corde sur un pied.',
    caution: 'À éviter en cas de douleur au tendon d\'Achille ou au mollet. Commence par des séries courtes.',
  },
  {
    id: 'rope_running_step',
    name: 'Corde à sauter, pas de course',
    target: 'Mollets et cadence',
    description: 'Saute à la corde en passant d\'un pied sur l\'autre, comme si tu courais sur place. Reste sur l\'avant du pied.',
    equipmentRequired: ['corde_a_sauter'],
    category: 'specific_calf',
    group: 'mollets',
    tips: 'Genoux bas et appuis légers : c\'est la cadence qui compte, pas la hauteur.',
    instructionHighlight: 'Avant du pied, appuis légers.',
    easier: 'Pieds joints, à rythme lent.',
    harder: 'Accélère, ou monte un peu les genoux.',
    caution: 'À éviter en cas de douleur au tendon d\'Achille ou au mollet. Commence par des séries courtes.',
  },
  {
    id: 'rope_single_leg',
    name: 'Corde à sauter sur un pied',
    target: 'Tendon d\'Achille et cheville',
    description: 'Saute à la corde sur un seul pied, petits rebonds sur l\'avant du pied. Change de pied à mi-temps.',
    equipmentRequired: ['corde_a_sauter'],
    category: 'specific_calf',
    group: 'mollets',
    tips: 'Le genou reste souple et dans l\'axe du pied. Arrête la série si la cheville s\'affaisse.',
    instructionHighlight: 'Petits rebonds, genou dans l’axe.',
    easier: 'Alterne 2 sauts sur chaque pied.',
    harder: 'Plus vite, sans poser l\'autre pied.',
    caution: 'À éviter en cas de douleur au tendon d\'Achille ou au mollet. Commence par des séries courtes.',
  },
  {
    id: 'marche_talons_inversion',
    name: 'Marche sur les talons',
    target: 'Jambier antérieur (devant du tibia)',
    description: 'Lève l\'avant des pieds et marche uniquement sur les talons.',
    equipmentRequired: [],
    category: 'specific_calf',
    group: 'mollets',
    tips: 'Ce muscle travaille à l\'opposé du mollet. Le renforcer équilibre le bas de la jambe.',
    instructionHighlight: 'Pointes de pieds le plus haut possible.',
    easier: 'Assis, lève et repose l\'avant des pieds, talons au sol.',
    harder: 'Dos au mur, pieds un peu avancés : lève et redescends les pointes des pieds sans t\'arrêter.',
  },
  {
    id: 'single_leg_balance',
    name: 'Équilibre sur un pied',
    target: 'Cheville et pied',
    description: 'Debout sur un pied, genou légèrement fléchi, l\'autre pied décollé. Tiens l\'équilibre sans te raccrocher. Change de pied à mi-temps.',
    equipmentRequired: [],
    category: 'specific_calf',
    group: 'mollets',
    tips: 'Le pied corrige sans arrêt : c\'est ce qui protège la cheville sur un terrain irrégulier.',
    instructionHighlight: 'Genou souple, regard fixe.',
    easier: 'Le bout des doigts posé contre un mur.',
    harder: 'Yeux fermés, ou debout sur un coussin.',
  },
  {
    id: 'shift_squat_goblet',
    name: 'Squat goblet latéral',
    target: 'Adducteurs et hanches',
    description: 'Ton poids contre la poitrine, pieds un peu plus écartés que les épaules. Descends en squat. En bas, décale le poids du corps sur la jambe gauche, reviens au centre, puis sur la jambe droite, reviens au centre et remonte.',
    equipmentRequired: ['poids_8kg'],
    category: 'specific_adductor',
    group: 'adducteurs',
    tips: 'Reste bas pendant tout le transfert : les adducteurs travaillent pour stabiliser le bassin.',
    instructionHighlight: 'Fesses basses pendant le transfert.',
    easier: 'Sans poids, et moins bas.',
    harder: 'Marque 2 secondes sur chaque jambe.',
  },
  {
    id: 'single_leg_bridge',
    name: 'Pont fessier sur une jambe',
    target: 'Fessiers et ischios',
    description: 'Sur le dos, genoux pliés, pieds au sol. Tends une jambe dans l\'axe de la cuisse, pousse dans le talon resté au sol et monte le bassin. Redescends sans poser les fesses. Change de jambe à mi-temps.',
    equipmentRequired: [],
    category: 'general',
    group: 'fessiers',
    tips: 'Serre les fessiers en haut, sans cambrer le bas du dos.',
    instructionHighlight: 'Pousse dans le talon, bassin horizontal.',
    easier: 'Les deux pieds au sol.',
    harder: 'Tiens 2 secondes en haut à chaque montée.',
  },
  {
    id: 'hamstring_bridge_chair',
    name: 'Pont ischios, pieds sur chaise',
    target: 'Ischios et fessiers',
    description: 'Sur le dos, talons posés sur l\'assise d\'une chaise, jambes presque tendues. Monte le bassin en poussant dans les talons, puis redescends lentement.',
    equipmentRequired: ['chaise'],
    category: 'general',
    group: 'fessiers',
    tips: 'Les ischios freinent la jambe à chaque foulée. Garde le bassin horizontal en haut.',
    instructionHighlight: 'Pousse dans les talons.',
    easier: 'Genoux plus pliés, fesses plus près de la chaise.',
    harder: 'Sur une jambe, en changeant de jambe à chaque tour.',
  },
  {
    id: 'side_lying_abduction',
    name: 'Abduction couché sur le côté',
    target: 'Moyen fessier',
    description: 'Allongé sur le côté, jambes tendues dans l\'axe du corps. Monte la jambe du dessus d\'environ 30 cm, pointe de pied vers l\'avant, puis redescends lentement. Change de côté à mi-temps.',
    equipmentRequired: [],
    category: 'general',
    group: 'fessiers',
    tips: 'Le moyen fessier stabilise le bassin à chaque appui. La jambe monte légèrement vers l\'arrière, jamais vers l\'avant.',
    instructionHighlight: 'Bassin immobile, le talon mène.',
    easier: 'Monte la jambe moins haut.',
    harder: 'Tiens 2 secondes en haut, ou pose ton poids sur la cuisse.',
  },
  {
    id: 'single_leg_rdl',
    name: 'Soulevé de terre sur une jambe',
    target: 'Ischios, fessiers et équilibre',
    description: 'Debout sur une jambe, genou légèrement fléchi. Penche le buste vers l\'avant en tendant l\'autre jambe derrière toi, dos droit, puis reviens. Change de jambe à mi-temps.',
    equipmentRequired: [],
    category: 'general',
    group: 'fessiers',
    tips: 'Le mouvement part des hanches. Descends tant que ton dos reste plat.',
    instructionHighlight: 'Dos plat, bassin face au sol.',
    easier: 'Pointe du pied arrière posée au sol, ou une main contre un mur.',
    harder: 'Tiens ton poids dans la main opposée à la jambe d\'appui.',
  },
  {
    id: 'bulgarian_split_squat',
    name: 'Fente bulgare',
    target: 'Quadriceps et fessiers',
    description: 'Dos à une chaise, pose le dessus du pied arrière sur l\'assise. Descends sur la jambe avant jusqu\'à ce que la cuisse soit presque parallèle au sol, puis remonte. Change de jambe à mi-temps.',
    equipmentRequired: ['chaise'],
    category: 'general',
    group: 'cuisses',
    tips: 'Le genou avant reste dans l\'axe du pied. Éloigne un peu le pied avant de la chaise pour garder le buste droit.',
    instructionHighlight: 'Le poids sur la jambe avant.',
    easier: 'Descends moins bas, une main contre un mur.',
    harder: 'Ton poids contre la poitrine.',
  },
  {
    id: 'side_plank',
    name: 'Gainage latéral',
    target: 'Obliques et moyen fessier',
    description: 'Sur le côté, en appui sur l\'avant-bras, coude sous l\'épaule. Soulève le bassin pour aligner tête, bassin et pieds. Change de côté à mi-temps.',
    equipmentRequired: [],
    category: 'abdos',
    group: 'gainage',
    tips: 'Le bassin ne s\'affaisse pas : pousse-le vers le plafond.',
    instructionHighlight: 'Bassin haut, corps aligné.',
    easier: 'Genoux pliés au sol.',
    harder: 'Lève la jambe du dessus.',
  },
  {
    id: 'dead_bug',
    name: 'Dead bug',
    target: 'Gainage profond (transverse)',
    description: 'Sur le dos, bras tendus vers le plafond, genoux pliés à 90° au-dessus des hanches. Tends lentement un bras derrière la tête et la jambe opposée, sans toucher le sol, puis reviens. Alterne.',
    equipmentRequired: [],
    category: 'abdos',
    group: 'gainage',
    tips: 'Le bas du dos reste plaqué au sol pendant tout le mouvement. Souffle en tendant.',
    instructionHighlight: 'Bas du dos collé au sol.',
    easier: 'Bouge seulement les jambes, bras tendus vers le plafond.',
    harder: '3 secondes pour tendre, 3 secondes pour revenir.',
  },
  {
    id: 'bird_dog',
    name: 'Bird dog',
    target: 'Lombaires et gainage',
    description: 'À quatre pattes, mains sous les épaules, genoux sous les hanches. Tends un bras devant toi et la jambe opposée derrière, tiens 2 secondes, puis reviens. Alterne.',
    equipmentRequired: [],
    category: 'abdos',
    group: 'gainage',
    tips: 'Le dos reste plat comme une table : imagine un verre d\'eau posé dessus.',
    instructionHighlight: 'Dos plat, bassin immobile.',
    easier: 'Tends seulement la jambe, les deux mains au sol.',
    harder: 'Entre chaque extension, ramène le coude et le genou sous le ventre.',
  },
];
